export const PLANNER_LABELS = {
  API: {
    CREATE_SPRINT_SUCCESS: "Sprint created successfully.",
    CREATE_SPRINT_ERROR: "Failed to create sprint.",
    GENERATE_SPRINTS_SUCCESS: "Sprint plan generation started.",
    GENERATE_SPRINTS_ERROR: "Failed to start sprint plan generation.",
    CREATE_TASK_SUCCESS: "Task created successfully.",
    CREATE_TASK_ERROR: "Failed to create task.",
    UPDATE_TASK_SUCCESS: "Task updated successfully.",
    UPDATE_TASK_ERROR: "Failed to update task.",
  },
  CONTROLS: {
    SPRINT_GROUP_ARIA: "Select sprint",
    SPRINT_PREFIX: "Sprint",
    NO_SPRINTS: "No sprints yet",
    NEW_TASK: "+ New Task",
    GENERATE_PLAN: "Generate Sprint Plan",
    GENERATING: "Generating…",
  },
  SUMMARY: {
    COMMITTED_LABEL: "Committed",
    COMPLETED_LABEL: "Completed",
    REMAINING_LABEL: "Remaining",
    POINTS_SUFFIX: "pts",
    NO_SPRINT_TITLE: "No active sprint",
    NO_SPRINT_DESCRIPTION:
      "Select a sprint or generate a sprint plan to see its summary.",
    NO_DATES: "No dates set",
  },
  STATUS: {
    PLANNED: "Planned",
    ACTIVE: "Active",
    COMPLETED: "Completed",
    ON_TRACK: "On Track",
    AT_RISK: "At Risk",
    BEHIND: "Behind Schedule",
  },
  COLUMNS: {
    TODO: "Todo",
    IN_PROGRESS: "In Progress",
    IN_REVIEW: "In Review",
    DONE: "Done",
    BLOCKED: "Blocked",
  },
  EMPTY: {
    NO_TASKS: "No tasks",
    LOAD_ERROR: "Failed to load tasks.",
    RETRY: "Retry",
    NO_SPRINT_SELECTED: "Select a sprint to view its tasks.",
    NO_PROJECT_TITLE: "No project selected",
    NO_PROJECT_DESCRIPTION: "Select a project to view and plan its sprints.",
    SPRINTS_LOAD_ERROR: "Failed to load sprints.",
  },
  BADGES: {
    CRITICAL: "Critical",
    MEDIUM: "Medium",
    LOW: "Low",
    HIGH: "High",
  },
  GENERATE_DIALOG: {
    TITLE: "Generating Sprint Plan…",
    SUBTITLE: "AI is decomposing approved user stories into sprints and tasks.",
    PENDING: "Generating sprint plan…",
    DONE_TITLE: "Sprint plan ready",
    DONE_SUBTITLE: "Your sprints have been generated.",
    CLOSE: "Close",
    START: "Start Generation",
    DESCRIPTION:
      "This uses AI to create sprints from your approved user stories. It may take a moment.",
  },
  FORM: {
    DIALOG_TITLE: "Create Task",
    DIALOG_DESCRIPTION: "Add a new task to the sprint backlog.",
    TITLE_LABEL: "Title",
    TITLE_PLACEHOLDER: "e.g. Implement GPS tracking API",
    DESCRIPTION_LABEL: "Description",
    DESCRIPTION_PLACEHOLDER: "Brief description of the task",
    PRIORITY_LABEL: "Priority",
    PRIORITY_PLACEHOLDER: "Select priority",
    TASK_TYPE_LABEL: "Task Type",
    TASK_TYPE_PLACEHOLDER: "e.g. feature, bug, chore",
    ESTIMATED_HOURS_LABEL: "Estimated Hours",
    ESTIMATED_HOURS_PLACEHOLDER: "e.g. 8",
    SPRINT_LABEL: "Sprint",
    SPRINT_PLACEHOLDER: "Select sprint",
    SPRINT_NONE: "No sprint (backlog)",
    DUE_DATE_LABEL: "Due Date",
    ASSIGNEE_LABEL: "Assignee",
    ASSIGNEE_PLACEHOLDER: "Assignee id (optional)",
    SUBMIT_BUTTON: "Create Task",
    PRIORITY_LOW: "Low",
    PRIORITY_MEDIUM: "Medium",
    PRIORITY_HIGH: "High",
    PRIORITY_CRITICAL: "Critical",
    VALIDATION: {
      TITLE_REQUIRED: "Title is required.",
      TITLE_MAX: "Title must be at most 255 characters.",
      DESCRIPTION_MAX: "Description must be at most 2000 characters.",
      TASK_TYPE_MAX: "Task type must be at most 50 characters.",
      ASSIGNEE_MAX: "Assignee must be at most 255 characters.",
      ESTIMATED_HOURS_INVALID: "Estimated hours must be a positive number.",
    },
  },
} as const;
