export const PLANNER_LABELS = {
  VIEW: {
    KANBAN: "Kanban",
    GANTT: "Gantt",
    GANTT_COMING_SOON: "Gantt view coming soon",
  },
  CONTROLS: {
    VIEW_TOGGLE_ARIA: "Board view",
    SPRINT_1: "Sprint 1 ✓",
    SPRINT_2: "Sprint 2 ✓",
    SPRINT_3: "Sprint 3",
    SPRINT_GROUP_ARIA: "Select sprint",
    NEW_TASK: "+ New Task",
    GENERATE_PLAN: "Generate Sprint Plan",
  },
  SUMMARY: {
    NAME: "Sprint 3",
    DATE_RANGE: "Jun 10 – Jun 28, 2026",
    COMMITTED_LABEL: "Committed",
    COMMITTED_VALUE: "38 pts",
    COMPLETED_LABEL: "Completed",
    COMPLETED_VALUE: "22 pts",
    REMAINING_LABEL: "Remaining",
    REMAINING_VALUE: "16 pts",
    STATUS: "Behind Schedule",
  },
  COLUMNS: {
    TODO: "Todo",
    IN_PROGRESS: "In Progress",
    IN_REVIEW: "In Review",
    DONE: "Done",
    BLOCKED: "Blocked",
  },
  EMPTY: {
    NO_TASKS: "No tasks",
  },
  BADGES: {
    CRITICAL: "Critical",
    MEDIUM: "Medium",
    LOW: "Low",
    HIGH: "High",
  },
  BLOCKED: {
    LABEL: "Blocked 52h",
  },
  TASKS: {
    ROUTE_OPTIMIZATION: "Route Optimization Engine",
    ANALYTICS_DASHBOARD: "Analytics Dashboard v2",
    GEOFENCE_ALERT: "Geofence Alert Service",
    RATE_CARD: "Rate Card Configuration UI",
    LOAD_BALANCER: "Load Balancer Health Check",
    GPS_TRACKING: "GPS Tracking WebSocket API",
    DRIVER_APP_FLOW: "Driver App — Delivery Flow",
    DRIVER_APP_UI: "Driver App UI Scaffolding",
    DB_MIGRATION: "Database Schema Migration",
    AUTH_JWT: "Auth JWT Implementation",
    HERE_MAPS: "HERE Maps API Integration",
    HERE_MAPS_REASON:
      "Waiting for API key approval from HERE Maps enterprise team. Escalated to Sarah.",
  },
  META: {
    ROUTE_OPTIMIZATION: "13 pts · Sarah C.",
    ANALYTICS_DASHBOARD: "8 pts · Raj M.",
    GEOFENCE_ALERT: "5 pts · Mike T.",
    RATE_CARD: "3 pts · Amy K.",
    LOAD_BALANCER: "2 pts · DevOps",
    GPS_TRACKING: "8 pts · Sarah C.",
    DRIVER_APP_FLOW: "5 pts · Amy K.",
    DRIVER_APP_UI: "8 pts · Jun 22",
    DB_MIGRATION: "5 pts · Jun 20",
    AUTH_JWT: "5 pts · Jun 19",
    HERE_MAPS: "13 pts · Raj M.",
    GPS_TRACKING_PROGRESS: "70% — 2 days left",
    DRIVER_APP_FLOW_PROGRESS: "45% — 3 days left",
  },
  DIALOG: {
    TITLE: "Generating Sprint Plan…",
    SUBTITLE: "AI is analyzing 18 approved user stories",
    STEP_1: "Analyzed user stories and dependencies",
    STEP_2: "Decomposed into 42 engineering tasks",
    STEP_3: "Assigning tasks to 3 sprints (40 pts each)…",
    STEP_4: "Suggesting assignees based on skills…",
    CANCEL: "Cancel",
  },
} as const;
