/** UI copy for the Proposal module. All user-visible strings live here. */
export const PROPOSAL_LABELS = {
  API: {
    GENERATE_SUCCESS: "Proposal generation started.",
    GENERATE_ERROR: "Failed to start proposal generation.",
    GENERATE_COMPLETE: "Proposal generated successfully.",
    GENERATE_FAILED: "Proposal generation failed.",
    UPDATE_SUCCESS: "Proposal updated successfully.",
    UPDATE_ERROR: "Failed to update proposal.",
    AI_EDIT_ERROR: "Failed to generate AI changes.",
  },
  PAGE: {
    NO_PROJECT_TITLE: "No project selected",
    NO_PROJECT_DESCRIPTION: "Select a project to view its proposal.",
    LOAD_ERROR: "Failed to load proposal.",
  },
  EMPTY: {
    TITLE: "No proposal yet",
    DESCRIPTION: "Generate an AI-drafted technical proposal for this project.",
  },
  HEADER: {
    EXPORT: "Export PDF",
    EXPORTING: "Exporting…",
    EDIT: "AI Edit",
    EDITING: "Editing…",
    EXPORT_ERROR: "Failed to export proposal as PDF.",
    GENERATE: "Generate Proposal",
    GENERATING: "Generating…",
    GENERATE_DISABLED_HINT: "Add requirements before generating a proposal.",
  },
  EDIT: {
    EDIT_BUTTON: "Edit",
    SAVE_BUTTON: "Save",
    SAVING: "Saving…",
    REMOVE_ROW_ARIA: "Remove row",
    ARCHITECTURE_RATIONALE_LABEL: "Rationale",
    ARCHITECTURE_COMPONENT_NAME_PLACEHOLDER: "Component name",
    ARCHITECTURE_COMPONENT_TECHNOLOGY_PLACEHOLDER: "Technology",
    ARCHITECTURE_COMPONENT_PURPOSE_PLACEHOLDER: "Purpose",
    ADD_COMPONENT: "Add component",
    TEAM_ROLE_PLACEHOLDER: "Role",
    TEAM_COUNT_PLACEHOLDER: "Count",
    TEAM_SKILLS_PLACEHOLDER: "Skills (comma-separated)",
    TEAM_RATIONALE_PLACEHOLDER: "Staffing rationale",
    ADD_MEMBER: "Add team member",
    TIMELINE_PHASE_PLACEHOLDER: "Phase name",
    TIMELINE_DURATION_PLACEHOLDER: "Weeks",
    TIMELINE_DELIVERABLES_PLACEHOLDER: "Deliverables (one per line)",
    ADD_PHASE: "Add phase",
    COST_ROLE_PLACEHOLDER: "Role",
    COST_MODULE_PLACEHOLDER: "Module",
    ADD_COST_ROW: "Add row",
    RISK_DESCRIPTION_PLACEHOLDER: "Risk description",
    RISK_IMPACT_PLACEHOLDER: "Impact",
    RISK_PROBABILITY_PLACEHOLDER: "Probability",
    RISK_MITIGATION_PLACEHOLDER: "Mitigation",
    ADD_RISK: "Add risk",
  },
  ASK_AI_DIALOG: {
    TITLE: "Ask AI to update proposal",
    DESCRIPTION_PLACEHOLDER:
      "Describe which section or field you'd like AI to update...",
    CANCEL: "Cancel",
    SUBMIT: "Update Proposal",
    GENERATING: "Generating changes…",
    PREVIEW_TITLE: "Review AI changes",
    CHANGE_SUMMARY_LABEL: "Summary of changes",
    DISCARD: "Discard",
    CONFIRM: "Confirm",
    CONFIRMING: "Saving…",
  },
  DOCUMENT: {
    EYEBROW: "Technical Proposal",
    SUBTITLE_PREPARED_BY: "Prepared by Simform Solutions",
  },
  EXECUTIVE_SUMMARY: {
    TITLE: "Executive Summary",
    EMPTY: "No executive summary provided yet.",
  },
  TECHNICAL_APPROACH: {
    TITLE: "Technical Approach",
    EMPTY: "No technical approach provided yet.",
  },
  ARCHITECTURE: {
    TITLE: "Proposed Architecture",
    RATIONALE_LABEL: "Rationale",
    COMPONENTS_LABEL: "Components",
    EMPTY: "Architecture details are not available yet.",
  },
  TEAM_COMPOSITION: {
    TITLE: "Team Composition",
    EMPTY: "Team composition is not available yet.",
  },
  TIMELINE: {
    TITLE: "Timeline",
    EMPTY: "Timeline is not available yet.",
    DURATION_VALUE: (weeks: number) => `${weeks} week${weeks === 1 ? "" : "s"}`,
  },
  COST_BREAKDOWN: {
    TITLE: "Effort & Cost Estimate",
    EMPTY: "Cost breakdown is not available yet.",
    COLUMN_ROLE: "Role",
    COLUMN_MODULE: "Module",
    COLUMN_DAYS: "Days",
    COLUMN_RATE: "Rate / Day",
    COLUMN_TOTAL: "Total",
    TOTAL_ROW_LABEL: "Total Engagement Cost",
    PENDING: "Pending",
    TOTAL_DAYS_VALUE: (days: number) => `${days} days`,
  },
  RISKS: {
    TITLE: "Risks",
    EMPTY: "No risks identified yet.",
    IMPACT_LABEL: "impact",
    PROBABILITY_LABEL: "probability",
  },
  STATUS: {
    DRAFT: "Draft",
    GENERATING: "Generating",
    COMPLETED: "Completed",
    APPROVED: "Approved",
    FAILED: "Failed",
  },
} as const;
