export const DASHBOARD_LABELS = {
  STATS: {
    RISK_SCORE: "Risk Score",
    RISK_SUFFIX: "/100",
    RISK_BADGE_LOW: "LOW",
    RISK_BADGE_MEDIUM: "MEDIUM",
    RISK_BADGE_HIGH: "HIGH",
    RISK_BADGE_CRITICAL: "CRITICAL",
    RISK_NOT_AVAILABLE: "—",
    COMPLETION: "Task Completion",
    COMPLETION_SUFFIX: "%",
    COMPLETION_CAPTION_TEMPLATE: "{completed}/{total} tasks",
    TOTAL_TASKS: "Total Tasks",
    TOTAL_TASKS_SUFFIX: "tasks",
    COMPLETED_TASKS: "Completed Tasks",
    COMPLETED_TASKS_SUFFIX: "tasks",
    OPEN_TASKS: "Open Tasks",
    OPEN_TASKS_SUFFIX: "tasks",
    OPEN_TASKS_ALERT_TEMPLATE: "⚠ {count} blocked",
    IN_PROGRESS_TASKS: "In Progress",
    IN_PROGRESS_TASKS_SUFFIX: "tasks",
    BLOCKED_TASKS: "Blocked Tasks",
    BLOCKED_TASKS_SUFFIX: "tasks",
    TEAM_SIZE: "Team Size",
    TEAM_SIZE_SUFFIX: "members",
  },
  BURNDOWN: {
    TITLE: "Sprint Burndown",
    SUBTITLE: "Remaining points over the sprint",
    IDEAL: "Ideal Burndown",
    ACTUAL: "Actual Remaining",
  },
  VELOCITY: {
    TITLE: "Velocity Trend",
    SUBTITLE: "Points completed per sprint",
  },
  OVERVIEW: {
    NO_CLIENT: "No client assigned",
    NO_DESCRIPTION: "No description added yet.",
    CREATED_PREFIX: "Created",
    TIMELINE: "Timeline",
    NOT_SCHEDULED: "Not scheduled",
    DUE_TODAY: "Due today",
    DAYS_REMAINING_TEMPLATE: "{days} days remaining",
    OVERDUE_TEMPLATE: "Overdue by {days} days",
    BUDGET: "Budget",
    DURATION: "Duration",
    DURATION_TEMPLATE: "{days} days",
    START: "Start",
    TARGET_END: "Target end",
    NOT_AVAILABLE: "—",
  },
} as const;
