/** All user-visible copy for the Requirements module. */
export const REQUIREMENTS_LABELS = {
  TABS: {
    DOCUMENTS: "Documents",
    REQUIREMENTS: "Requirements",
    REQUIREMENTS_BADGE: "24",
    USER_STORIES: "User Stories",
    USER_STORIES_BADGE: "18",
  },
  UPLOAD: {
    HEADLINE: "Drop your RFP or requirement document here",
    HINT: "PDF, DOCX, TXT — up to 50MB",
    BROWSE: "Browse Files",
  },
  DOCUMENTS: {
    COLUMN_FILE: "File",
    COLUMN_TYPE: "Type",
    COLUMN_UPLOADED: "Uploaded",
    COLUMN_STATUS: "Status",
    COLUMN_ACTION: "Action",
  },
  REQUIREMENTS: {
    SEARCH_PLACEHOLDER: "Search requirements…",
    FILTER_LABEL: "Filter by type",
    FILTER_ALL: "All Types",
    FILTER_FUNCTIONAL: "Functional",
    FILTER_NON_FUNCTIONAL: "Non-Functional",
    FILTER_RISK: "Risk",
    GENERATE_STORIES: "Generate Stories →",
    FUNCTIONAL_TITLE: "Functional Requirements (14)",
    NON_FUNCTIONAL_TITLE: "Non-Functional Requirements (6)",
    SHOW_FUNCTIONAL_MORE: "+ Show 11 more",
    SHOW_NON_FUNCTIONAL_MORE: "+ Show 4 more",
    EDIT_ARIA: "Edit requirement",
  },
  USER_STORIES: {
    EDIT_ARIA: "Edit user story",
    COLLAPSE_ARIA: "Toggle epic",
    GIVEN: "Given",
    WHEN: "When",
    THEN: "Then",
  },
  STATUS: {
    PROCESSED: "Processed",
    PROCESSING: "Processing",
    FAILED: "Failed",
    LOW: "Low",
    HIGH: "High",
    MEDIUM: "Medium",
    CRITICAL: "Critical",
    AT_RISK: "At Risk",
  },
  ACTIONS: {
    VIEW_RESULTS: "View Results",
    PROCESSING: "Processing…",
    RETRY: "Retry",
    PENDING: "Pending…",
  },
  STATE: {
    LOADING: "Loading…",
    DOCUMENTS_ERROR: "Failed to load documents. Please try again.",
    DOCUMENTS_EMPTY: "No documents uploaded yet.",
    REQUIREMENTS_ERROR: "Failed to load requirements. Please try again.",
    REQUIREMENTS_EMPTY: "No requirements found.",
    STORIES_ERROR: "Failed to load user stories. Please try again.",
    STORIES_EMPTY: "No user stories yet. Generate them from your requirements.",
  },
  TOAST: {
    UPLOAD_SUCCESS: "Document uploaded successfully.",
    UPLOAD_ERROR: "Failed to upload document.",
    PROCESS_SUCCESS: "Document processing started.",
    PROCESS_ERROR: "Failed to process document.",
    GENERATE_STORIES_SUCCESS: "User stories generated successfully.",
    GENERATE_STORIES_ERROR: "Failed to generate user stories.",
    UPDATE_SUCCESS: "Changes saved successfully.",
    UPDATE_ERROR: "Failed to save changes.",
    INVALID_FILE_TYPE:
      "Invalid file type. Only PDF, DOCX, and TXT files are allowed.",
  },
  DYNAMIC: {
    STORY_POINTS: (points: number) => `${points} pts`,
    UPLOADED_COUNT: (count: number) => `Uploaded Files (${count})`,
    FILE_SIZE_KB: (kb: string) => `${kb} KB`,
  },
  UPLOADED_FILES_TITLE: "Uploaded Files",
  REMOVE_ARIA: "Remove file",
  UPLOAD_INPUT_ARIA: "Upload document files",
  DOCS_DATA: {
    DOC1_NAME: "TechFlow_Logistics_RFP.pdf",
    DOC1_SIZE: "4.2 MB",
    DOC1_TYPE: "RFP",
    DOC1_UPLOADED: "Jun 20, 2026",
    DOC2_NAME: "TechFlow_Technical_Specs_v2.docx",
    DOC2_SIZE: "1.8 MB",
    DOC2_TYPE: "Spec",
    DOC2_UPLOADED: "Jun 21, 2026",
    DOC3_NAME: "Meeting_Notes_Jun22.txt",
    DOC3_SIZE: "24 KB",
    DOC3_TYPE: "Notes",
    DOC3_UPLOADED: "Jun 22, 2026",
    TILE_PDF: "PDF",
    TILE_DOC: "DOC",
    TILE_TXT: "TXT",
    VIEW_RESULTS: "View Results",
    PENDING: "Pending…",
  },
  FR_DATA: {
    FR1_TITLE: "Real-time GPS fleet tracking with 30s refresh interval",
    FR1_SUBTITLE: "Support 450 concurrent vehicle connections via WebSocket",
    FR2_TITLE:
      "AI-powered route optimization based on traffic, time windows, and load",
    FR2_SUBTITLE: "Integrate HERE Maps API for routing calculations",
    FR3_TITLE: "Driver mobile app with delivery confirmation and photo capture",
    FR3_SUBTITLE: "iOS and Android, offline-first with sync on reconnect",
  },
  NFR_DATA: {
    NFR1_TITLE: "API response time ≤200ms at p95 under 10K concurrent users",
    NFR2_TITLE: "99.9% uptime SLA with automated failover",
  },
  EPIC_DATA: {
    EPIC1_TITLE: "Fleet Tracking & Visibility",
    EPIC1_SUMMARY: "4 stories · 32 pts",
    EPIC2_TITLE: "Route Optimization",
    EPIC2_SUMMARY: "3 stories · 21 pts",
    EPIC2_NOTE:
      "Route optimization not started — 13 pts remaining. Pairing Sarah & Raj.",
    US1_TITLE: "Real-time vehicle position map",
    US1_POINTS: "8 pts",
    US1_GIVEN: "a dispatcher is on the Fleet Map view",
    US1_WHEN: "a vehicle updates its GPS position",
    US1_THEN: "the vehicle marker moves on the map within 30 seconds",
    US2_TITLE: "Vehicle status and alert panel",
    US2_POINTS: "5 pts",
    US2_GIVEN: "any vehicle goes offline or enters a geofence violation",
    US2_WHEN: "the condition is detected by the tracking service",
    US2_THEN: "an alert appears in the dispatcher dashboard within 10 seconds",
  },
} as const;
