/** All user-visible copy for the Requirements module. */
export const REQUIREMENTS_LABELS = {
  API: {
    UPLOAD_SUCCESS: "Document uploaded successfully.",
    UPLOAD_ERROR: "Failed to upload document.",
    PROCESS_SUCCESS: "Document processing started.",
    PROCESS_ERROR: "Failed to start document processing.",
    UPDATE_SUCCESS: "Requirement updated successfully.",
    UPDATE_ERROR: "Failed to update requirement.",
    GENERATE_STORIES_SUCCESS: "User story generation started.",
    GENERATE_STORIES_ERROR: "Failed to start user story generation.",
    STORY_UPDATE_SUCCESS: "User story updated successfully.",
    STORY_UPDATE_ERROR: "Failed to update user story.",
    CLARIFICATION_ERROR: "Failed to submit your answers.",
    SKIP_ERROR: "Failed to skip clarifications.",
  },
  TABS: {
    DOCUMENTS: "Documents",
    REQUIREMENTS: "Requirements",
    USER_STORIES: "User Stories",
  },
  UPLOAD: {
    HEADLINE: "Drop your RFP or requirement document here",
    HINT: "PDF, DOCX, TXT — up to 50MB",
    BROWSE: "Browse Files",
  },
  UPLOAD_FLOW: {
    DIALOG_TITLE: "Document analysis",
    UPLOADING_TITLE: "Uploading document…",
    UPLOADING_DESC: "Sending your file to the server.",
    ANALYZING_TITLE: "Analyzing document…",
    ANALYZING_DESC:
      "We're reading your document to prepare clarification questions. This may take a moment.",
    QUESTIONS_TITLE: "Clarification questions",
    QUESTIONS_DESC:
      "Answer these to improve the generated requirements. You can skip any or all of them.",
    PROCESSING_TITLE: "Processing document…",
    PROCESSING_DESC:
      "Generating requirements from your document and answers. This may take a moment.",
    DONE_TITLE: "All set!",
    DONE_DESC:
      "Your document has been processed. Requirements are now available.",
    ERROR_TITLE: "Something went wrong",
    ERROR_DESC:
      "We couldn't finish processing this document. Please try uploading it again.",
    SKIP: "Skip all",
    SUBMIT: "Submit answers",
    CLOSE: "Close",
    DONE_BUTTON: "Done",
    ANSWER_PLACEHOLDER: "Add your own answer (optional)…",
    RATIONALE_LABEL: "Why we're asking",
    OTHER_LABEL: "Your answer",
    STEP_ANALYZE: "Analyze",
    STEP_QUESTIONS: "Questions",
    STEP_PROCESS: "Process",
    QUESTIONS_EMPTY: "No clarification questions for this document.",
    QUESTIONS_ERROR: "Failed to load clarification questions.",
    CONTINUE: "Continue",
  },
  DOCUMENTS: {
    COLUMN_FILE: "File",
    COLUMN_TYPE: "Type",
    COLUMN_UPLOADED: "Uploaded",
    COLUMN_STATUS: "Status",
    COLUMN_ACTION: "Action",
  },
  REQUIREMENTS: {
    SEARCH_PLACEHOLDER: "Search requirements…",
    FILTER_LABEL: "Filter by type",
    FILTER_ALL: "All Types",
    FILTER_FUNCTIONAL: "Functional",
    FILTER_NON_FUNCTIONAL: "Non-Functional",
    FILTER_RISK: "Risk",
    GENERATE_STORIES: "Generate Stories →",
    FUNCTIONAL_TITLE: "Functional Requirements",
    NON_FUNCTIONAL_TITLE: "Non-Functional Requirements",
    EDIT_ARIA: "Edit requirement",
  },
  USER_STORIES: {
    EDIT_ARIA: "Edit user story",
    GIVEN: "Given",
    WHEN: "When",
    THEN: "Then",
  },
  STATUS: {
    PROCESSED: "Processed",
    PROCESSING: "Processing",
    FAILED: "Failed",
    LOW: "Low",
    HIGH: "High",
    MEDIUM: "Medium",
    CRITICAL: "Critical",
    AT_RISK: "At Risk",
  },
  ACTIONS: {
    VIEW_RESULTS: "View Results",
    PROCESSING: "Processing…",
    RETRY: "Retry",
    PENDING: "Pending…",
  },
  STATE: {
    LOADING: "Loading…",
    DOCUMENTS_ERROR: "Failed to load documents. Please try again.",
    DOCUMENTS_EMPTY: "No documents uploaded yet.",
    REQUIREMENTS_ERROR: "Failed to load requirements. Please try again.",
    REQUIREMENTS_EMPTY: "No requirements found.",
    STORIES_ERROR: "Failed to load user stories. Please try again.",
    STORIES_EMPTY: "No user stories yet. Generate them from your requirements.",
  },
  TOAST: {
    UPLOAD_SUCCESS: "Document uploaded successfully.",
    UPLOAD_ERROR: "Failed to upload document.",
    PROCESS_SUCCESS: "Document processing started.",
    PROCESS_ERROR: "Failed to process document.",
    GENERATE_STORIES_SUCCESS: "User stories generated successfully.",
    GENERATE_STORIES_ERROR: "Failed to generate user stories.",
    UPDATE_SUCCESS: "Changes saved successfully.",
    UPDATE_ERROR: "Failed to save changes.",
    INVALID_FILE_TYPE:
      "Invalid file type. Only PDF, DOCX, and TXT files are allowed.",
  },
  DYNAMIC: {
    STORY_POINTS: (points: number) => `${points} pts`,
    UPLOADED_COUNT: (count: number) => `Uploaded Files (${count})`,
    FILE_SIZE_KB: (kb: string) => `${kb} KB`,
    EPIC_SUMMARY: (storyCount: number, points: number) =>
      `${storyCount} stories · ${points} pts`,
  },
  UPLOADED_FILES_TITLE: "Uploaded Files",
  REMOVE_ARIA: "Remove file",
  UPLOAD_INPUT_ARIA: "Upload document files",
  DOCS_DATA: {
    TILE_PDF: "PDF",
    TILE_DOC: "DOC",
    TILE_TXT: "TXT",
  },
  FORM: {
    REQUIREMENT_EDIT_TITLE: "Edit Requirement",
    REQUIREMENT_EDIT_DESCRIPTION: "Update the requirement details below.",
    STORY_EDIT_TITLE: "Edit User Story",
    STORY_EDIT_DESCRIPTION: "Update the user story details below.",
    TITLE_LABEL: "Title",
    DESCRIPTION_LABEL: "Description",
    PRIORITY_LABEL: "Priority",
    STATUS_LABEL: "Status",
    TYPE_LABEL: "Type",
    STORY_LABEL: "Story",
    ACCEPTANCE_CRITERIA_LABEL: "Acceptance Criteria",
    STORY_POINTS_LABEL: "Story Points",
    EPIC_LABEL: "Epic",
    FEATURE_LABEL: "Feature",
    SAVE_BUTTON: "Save Changes",
    VALIDATION: {
      TITLE_REQUIRED: "Title is required.",
      TITLE_MAX: "Title must be 255 characters or fewer.",
      DESCRIPTION_MAX: "Description must be 2000 characters or fewer.",
      STORY_REQUIRED: "Story is required.",
      STORY_MAX: "Story must be 500 characters or fewer.",
      ACCEPTANCE_CRITERIA_MAX:
        "Acceptance criteria must be 2000 characters or fewer.",
      STORY_POINTS_INVALID: "Story points must be a non-negative number.",
      EPIC_MAX: "Epic must be 255 characters or fewer.",
      FEATURE_MAX: "Feature must be 255 characters or fewer.",
    },
  },
} as const;
